### PR TITLE
Flutter 3.10 Breaks Some Things Related to Text Editing

### PR DESCRIPTION
**Pull request by Satsrag**
I copied from the Flutter `3.10`. Below are the changes I made:

* Updated the dart version to 3.x.
* Compatible with the  `ContentInsertionConfiguration`.
* Compatible with the `TextSelectionGestureDetector` constructor.

### CODE REVIEW

**Review by suragch — APPROVED** [review]
Looks great! Thank you. I'll do a little testing and then publish the next version.

**Comment by suragch** [comment]
Published as mongol 5.0.0

**Comment by suragch** [comment]
@Satsrag I sent you an invite to be a contributor to this repository. You can make direct changes without waiting for me to approve them. I'd just request that you open a GitHub issue to document the kinds of changes you are making. That will also notify me so that we don't get merge requests if I'm about to make some changes at the same time. If you are making major changes, creating a new temporary branch would probably be good too. Thank you for your work.

**Comment by Satsrag** [comment]
I accepted it. Thank you for trusting me.

**Comment by amjil** [comment]
@suragch @Satsrag You guys both awesome， Thank you

**Pull request merged**
